[build]
target = "thumbv7em-none-eabihf"    # Cortex-M4F, hardware single-precision FPU

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F405RGTx"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"
